services:
  sveltessr:
    image: node:23-alpine
    working_dir: /usr/src/app
    volumes:
      - ./node:/usr/src/app
      - ./src:/var/www/html:ro # read-only access to PHP source files
    command: sh -c "npm install && npm start"
    networks:
      - lemp-network
    environment:
      - SVELTE_SRC_PATH=/var/www/html/dist-ssr

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - lemp-network

  php:
    image: php:8.3-fpm
    volumes:
      - ./src:/var/www/html
    networks:
      - lemp-network
    environment:
      - SVELTE_SSR_URL=http://sveltessr:3000

networks:
  lemp-network:
    driver: bridge
